### ISSUE TITLE
Getting KeyError

### ISSUE THREAD

**Issue by fosils** [djrobstep/migra#10]
I just attempted to use Migra for the first time. unfortunatelly I got the following error:
Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\migra.exe\__main__.py", line 9, in <module>
  File "c:\python34\lib\site-packages\migra\command.py", line 73, in do_command
    status = run(args)
  File "c:\python34\lib\site-packages\migra\command.py", line 52, in run
    m = Migration(ac0, ac1)
  File "c:\python34\lib\site-packages\migra\migra.py", line 20, in __init__
    self.changes.i_from = get_inspector(x_from)
  File "c:\python34\lib\site-packages\schemainspect\get.py", line 19, in get_inspector
    return ic(c)
  File "c:\python34\lib\site-packages\schemainspect\pg\__init__.py", line 331, in __init__
    super(PostgreSQL, self).__init__(c, include_internal)
  File "c:\python34\lib\site-packages\schemainspect\inspector.py", line 25, in __init__
    self.load_all()
  File "c:\python34\lib\site-packages\schemainspect\pg\__init__.py", line 340, in load_all
    self.load_deps()
  File "c:\python34\lib\site-packages\schemainspect\pg\__init__.py", line 357, in load_deps
    self.selectables[x_dependent_on].dependents.append(x)
KeyError: '"gui"."get_current_user"()'

The function definition for that function is:
CREATE OR REPLACE FUNCTION "gui"."get_current_user"()
  RETURNS "pg_catalog"."varchar" AS $BODY$
SELECT current_setting('session.username')

$BODY$
  LANGUAGE 'sql' VOLATILE STRICT  COST 100
;

ALTER FUNCTION "gui"."get_current_user"() OWNER TO "xunlight";

I am using Python 3.4 on windows. What other kinds of informations should I provide?

**Comment by fosils** [comment]
Here is a screenshot of the dependencies of gui.get_current_user() function:
https://www.screencast.com/t/4VWiqzcFp

**Comment by djrobstep** [comment]
Hi there, really appreciate you filing this issue!

Unfortunately support for function tracking is still somewhat unstable. You've hit a known issue with schemainspect, the library that migra uses to get information on database objects.

I'm currently working on a fix, and the next release should feature much better and more reliable function tracking support. I hope to roll it out in the next few days.

**Comment by fosils** [comment]
Wow! Awesome!

On Oct 25, 2017 02:28, "djrobstep" <notifications@github.com> wrote:

Hi there, really appreciate you filing this issue!

Unfortunately support for function tracking is still somewhat unstable.
You've hit a known issue with schemainspect, the library that migra uses to
get information on database objects.

I'm currently working on a fix, and the next release should feature much
better and more reliable function tracking support. I hope to roll it out
in the next few days.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/djrobstep/migra/issues/10#issuecomment-339176241>, or mute
the thread

**Comment by djrobstep** [comment]
This should be fixed now. Could you try upgrading your migra installation (make sure schemainspect is migrated too) and see if it now works as expected for you?

**Comment by fosils** [comment]
Awesome! That solved it! I upgraded and re-ran it. This time I am getting this error:

C:\Users\Andersen Innovation>migra --unsafe postgresql://xunlight:benjaMin11111111@test-db.cbktrbpgzmex.eu-central-1.rds.amazonaws.com:5732/test postgresql://xunlight:benjaMin11111111@production-db.cbktrbpgzmex.eu-central-1.rds.amazonaws.com:5732/dama86dd4g3vj6
Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\migra.exe\__main__.py", line 9, in <module>
  File "c:\python34\lib\site-packages\migra\command.py", line 73, in do_command
    status = run(args)
  File "c:\python34\lib\site-packages\migra\command.py", line 60, in run
    print(m.sql, file=out)
  File "c:\python34\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xf8' in position 27819: character maps to <undefined>

**Comment by fosils** [comment]
Awesome! That solved it! I upgraded and re-ran it. This time I am getting this error:

Traceback (most recent call last):
File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
"main", mod_spec)
File "c:\python34\lib\runpy.py", line 85, in run_code
exec(code, run_globals)
File "C:\Python34\Scripts\migra.exe_main.py", line 9, in 
File "c:\python34\lib\site-packages\migra\command.py", line 73, in do_command
status = run(args)
File "c:\python34\lib\site-packages\migra\command.py", line 60, in run
print(m.sql, file=out)
File "c:\python34\lib\encodings\cp437.py", line 19, in encode
return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xf8' in position 27819: character maps to

**Comment by djrobstep** [comment]
This looks like a problem with your terminal being unable to print certain unicode characters (migra prints unencoded text and lets your terminal handle it, which I think is the correct approach). I'll close this issue for now as the initial problem is solved, feel free to create a new one for this if you continue to have trouble, we can possibly add some more informative error handling for this scenario.

**Comment by fosils** [comment]
Perfect! Thank you for your help. I will attempt on another terminal.
