### ISSUE TITLE
Cannot install... please help

### ISSUE THREAD

**Issue by demian85** [djrobstep/migra#106]
Can someone please help me understand this Python shit? I'm using MacOS and I don't understand how to install this.
`migra[pg]` is not even a package...

```
pip3 install migra[pg]
zsh: no matches found: migra[pg]
```
So I had to install just `migra`

Problem now is:

```bash
migra "postgresql://xxxx.us-west-2.rds.amazonaws.com/postgres" "postgres://postgres:@localhost:5432/postgres"
Traceback (most recent call last):
  File "/usr/local/bin/migra", line 8, in <module>
    sys.exit(do_command())
  File "/usr/local/lib/python3.7/site-packages/migra/command.py", line 101, in do_command
    status = run(args)
  File "/usr/local/lib/python3.7/site-packages/migra/command.py", line 71, in run
    with arg_context(args.dburl_from) as ac0, arg_context(args.dburl_target) as ac1:
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/migra/command.py", line 19, in arg_context
    with S(x) as s:
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/sqlbag/sqla.py", line 141, in S
    Session = get_scoped_session_maker(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sqlbag/sqla.py", line 163, in get_scoped_session_maker
    sessionmaker(bind=create_engine(*args, **kwargs)), scopefunc=scopefunc
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/__init__.py", line 479, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 737, in dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
➜  rlink-platform git:(master) pip3 install psycopg2
Collecting psycopg2
  Downloading https://files.pythonhosted.org/packages/84/d7/6a93c99b5ba4d4d22daa3928b983cec66df4536ca50b22ce5dcac65e4e71/psycopg2-2.8.4.tar.gz (377kB)
     |████████████████████████████████| 378kB 2.9MB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/mt/q9wkcrhd3p5bnkv7zvg5kykr0000gn/T/pip-install-z2e1huin/psycopg2/setup.py'"'"'; __file__='"'"'/private/var/folders/mt/q9wkcrhd3p5bnkv7zvg5kykr0000gn/T/pip-install-z2e1huin/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/mt/q9wkcrhd3p5bnkv7zvg5kykr0000gn/T/pip-install-z2e1huin/psycopg2/pip-egg-info
         cwd: /private/var/folders/mt/q9wkcrhd3p5bnkv7zvg5kykr0000gn/T/pip-install-z2e1huin/psycopg2/
    Complete output (23 lines):
    running egg_info
    creating /private/var/folders/mt/q9wkcrhd3p5bnkv7zvg5kykr0000gn/T/pip-install-z2e1huin/psycopg2/pip-egg-info/psycopg2.egg-info
    writing /private/var/folders/mt/q9wkcrhd3p5bnkv7zvg5kykr0000gn/T/pip-install-z2e1huin/psycopg2/pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to /private/var/folders/mt/q9wkcrhd3p5bnkv7zvg5kykr0000gn/T/pip-install-z2e1huin/psycopg2/pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to /private/var/folders/mt/q9wkcrhd3p5bnkv7zvg5kykr0000gn/T/pip-install-z2e1huin/psycopg2/pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file '/private/var/folders/mt/q9wkcrhd3p5bnkv7zvg5kykr0000gn/T/pip-install-z2e1huin/psycopg2/pip-egg-info/psycopg2.egg-info/SOURCES.txt'

    Error: pg_config executable not found.

    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.

    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.``` 

Thanks!

**Comment by ThiefMaster** [comment]
You use a fancy shell (zsh) so you should know about its features. One of them is that it uses `[]` in globs and and (depending on its configuration) rejects commands containing globs not matching anything instead of keeping them as-is (like e.g. bash does).

So "this python shit" isn't broken, you simply need to use quotes, i.e. `pip install 'migra[pg]'`

And the error trying to install psycopg2 is pretty clear, it even tells you an alternative that does not require you to install any postgres dev dependencies...

**Comment by djrobstep** [comment]
@ThiefMaster is on the money here with the solutions.

I can see how the bracket error could be confusing so we can possibly add a note for that.

Unfortunately issues like these aren't anything migra-specific, and stem from broader issues with shells, with the postgres driver and with the wider python ecosystem, which has become increasingly fragmented and more complex recently with changes to pip and with the rise of alternative package installers like poetry etc. 

It's hard to document these issues thoroughly without documenting the whole ecosystem!
