### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by YaTree** [djrobstep/migra#11]
Hi.

I got a problem:

`
Traceback (most recent call last):
  File "/usr/local/bin/migra", line 11, in <module>
    sys.exit(do_command())
  File "/usr/local/lib/python2.7/dist-packages/migra/command.py", line 73, in do_command
    status = run(args)
  File "/usr/local/lib/python2.7/dist-packages/migra/command.py", line 52, in run
    m = Migration(ac0, ac1)
  File "/usr/local/lib/python2.7/dist-packages/migra/migra.py", line 20, in __init__
    self.changes.i_from = get_inspector(x_from)
  File "/usr/local/lib/python2.7/dist-packages/schemainspect/get.py", line 19, in get_inspector
    return ic(c)
  File "/usr/local/lib/python2.7/dist-packages/schemainspect/pg/__init__.py", line 337, in __init__
    super(PostgreSQL, self).__init__(c, include_internal)
  File "/usr/local/lib/python2.7/dist-packages/schemainspect/inspector.py", line 25, in __init__
    self.load_all()
  File "/usr/local/lib/python2.7/dist-packages/schemainspect/pg/__init__.py", line 348, in load_all
    self.load_deps_all()
  File "/usr/local/lib/python2.7/dist-packages/schemainspect/pg/__init__.py", line 391, in load_deps_all
    'dependents'
  File "/usr/local/lib/python2.7/dist-packages/schemainspect/pg/__init__.py", line 378, in get_related_for_item
.....
.....
 File "/usr/local/lib/python2.7/dist-packages/schemainspect/pg/__init__.py", line 375, in get_related_for_item
    for _ in get_related_for_item(d, att)
  File "/usr/local/lib/python2.7/dist-packages/schemainspect/pg/__init__.py", line 375, in get_related_for_item
    for _ in get_related_for_item(d, att)
  File "/usr/local/lib/python2.7/dist-packages/schemainspect/pg/__init__.py", line 372, in get_related_for_item
    return [item.signature] + [
  File "/usr/local/lib/python2.7/dist-packages/schemainspect/pg/__init__.py", line 116, in signature
    return '{}({})'.format(self.quoted_full_name, self.identity_arguments)
  File "/usr/local/lib/python2.7/dist-packages/schemainspect/inspected.py", line 9, in quoted_full_name
    quoted_identifier(self.schema), quoted_identifier(self.name))
  File "/usr/local/lib/python2.7/dist-packages/schemainspect/misc.py", line 33, in quoted_identifier
    identifier, remainder = identifier.split('(', 1)
RuntimeError: maximum recursion depth exceeded` 

We are using pg 9.6, in our database structure we have inheritance for tables, probably this may make some loops.

How can I fix this or avoid?

**Comment by djrobstep** [comment]
This should be fixed now. Could you try upgrading your `migra` installation (make sure `schemainspect` is migrated too) and see if it now works as expected for you?

**Comment by YaTree** [comment]
I got it :) Thx!
