### ISSUE TITLE
Migra faults on syncing between Postgres 11 Alpine and RDS Postgres 11 instance

### ISSUE THREAD

**Issue by autumnjolitz** [djrobstep/migra#112]
I upgraded a postgres 10 install to postgres 11 on RDS, then adjusted my source database images to pull from `postgres:11-alpine`

I expected a sync between databases to just work, given they were the same major version.

The following error occurs with both postgres 11 -> postgres 11 and postgres 10 -> postgres 11 syncing:

```
Traceback (most recent call last):
  File "/usr/local/bin/migra", line 8, in <module>
    sys.exit(do_command())
  File "/usr/local/lib/python3.7/site-packages/migra/command.py", line 101, in do_command
    status = run(args)
  File "/usr/local/lib/python3.7/site-packages/migra/command.py", line 78, in run
    m.add_all_changes(privileges=args.with_privileges)
  File "/usr/local/lib/python3.7/site-packages/migra/migra.py", line 79, in add_all_changes
    self.add(self.changes.selectables())
  File "/usr/local/lib/python3.7/site-packages/migra/changes.py", line 212, in get_selectable_changes
    tables_from, tables_target
  File "/usr/local/lib/python3.7/site-packages/migra/util.py", line 14, in differences
    modified = od((k, b[k]) for k in sorted(keys_common) if a[k] != b[k])
  File "/usr/local/lib/python3.7/site-packages/migra/util.py", line 14, in <genexpr>
    modified = od((k, b[k]) for k in sorted(keys_common) if a[k] != b[k])
  File "/usr/local/lib/python3.7/site-packages/schemainspect/inspected.py", line 30, in __ne__
    return not self == other
  File "/usr/local/lib/python3.7/site-packages/schemainspect/inspected.py", line 208, in __eq__
    dict(self.columns) == dict(other.columns),
  File "/usr/local/lib/python3.7/site-packages/schemainspect/inspected.py", line 72, in __eq__
    and self.enum == other.enum
  File "/usr/local/lib/python3.7/site-packages/schemainspect/pg/obj.py", line 515, in __eq__
    self.name == other.name,
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by djrobstep** [comment]
Thanks for filing this! Can you give me a schema that reproduces this error? Try to cut it down as much as possible to the smallest schema that still makes it happen.

**Comment by autumnjolitz** [comment]
Unfortunately I've not isolated a schema that produces this yet.

This may be a security issue, as when I create the postgres container with user root, password venableroot, it just works, but when I pick another username and longer password, it blows up.

If I change schemainspect/inspected.py on line 64 to:
```
    def __eq__(self, other):
        try:
            return (
                self.name == other.name
                and self.dbtype == other.dbtype
                and self.dbtypestr == other.dbtypestr
                and self.pytype == other.pytype
                and self.default == other.default
                and self.not_null == other.not_null
                and self.enum == other.enum
                and self.collation == other.collation
            )
        except AttributeError:
            print(f'{self} threw an attribute error comparing to {other}!!!')
            raise
```

I get 
```
ColumnInfo(collation=None, dbtype='blueprint_outcome_behaviors', dbtypestr='blueprint_outcome_behaviors', default=None, enum=None, is_enum=False, name='outcome_behavior', not_null=True, pytype=<class 'NoneType'>) threw an attribute error comparing to ColumnInfo(collation=None, dbtype='blueprint_outcome_behaviors', dbtypestr='blueprint_outcome_behaviors', default=None, enum=InspectedEnum(elements=['maximize', 'minimize'], name='blueprint_outcome_behaviors', schema='aible'), is_enum=True, name='outcome_behavior', not_null=True, pytype=<class 'NoneType'>)!!!
```

**Comment by autumnjolitz** [comment]
Furthermore, when I run the sql from schemainspect https://github.com/djrobstep/schemainspect/blob/master/schemainspect/pg/sql/enums.sql#L1-L26

This is where it gets confusing.

The remote database possesses the enum `blueprint_outcome_behaviors`
```
postgres=> SELECT enum_range(NULL::blueprint_outcome_behaviors);
     enum_range
---------------------
 {maximize,minimize}
(1 row)

postgres=>
```

But the query at https://github.com/djrobstep/schemainspect/blob/master/schemainspect/pg/sql/enums.sql#L1-L26 does not show it!

**Comment by autumnjolitz** [comment]
Okay, when I remove `and e.objid is null` from the query, I see the missing enum that's been causing this issue!

**Comment by autumnjolitz** [comment]
The objid of the broken enum is `17166` which resolves to:
```
aible=>   select
aible->       objid
aible->   from
aible->       pg_depend d
aible->   WHERE
aible->       d.refclassid = 'pg_extension'::regclass AND ^C
aible=>
aible=>   select
aible->       *
aible->   from
aible->       pg_depend d
aible->   WHERE
aible->       d.refclassid = 'pg_extension'::regclass AND objid = 17166
aible-> ;
 classid | objid | objsubid | refclassid | refobjid | refobjsubid | deptype
---------+-------+----------+------------+----------+-------------+---------
    2605 | 17166 |        0 |       3079 |    16408 |           0 | e
```

**Comment by autumnjolitz** [comment]
Soooo somehow the RDS upgrade from postgres 10 to postgres 11 ended up with pg_extension -> pg_cast -> this enum? 😕

**Comment by autumnjolitz** [comment]
This is extra weird because the enum in question has never been used in any other context than:

```
CREATE TABLE tablename (
     -- snip
    behavior blueprint_outcome_behaviors NOT NULL,
    -- snip
)
```

I'm at a loss as to what to do next - either the sql for enum's here is changed or we figure out a way to detect/break this strange dependency in extension_oids. I've always used migra to manage this particular (currently used as a test) database, so I'm extremely confused as to how this could have happened!

**Comment by autumnjolitz** [comment]
Looking closer:

```
aible=> SELECT 2605::regclass;;
 regclass
----------
 pg_cast
(1 row)

aible=> SELECT 3079::regclass;;
   regclass
--------------
 pg_extension
(1 row)

aible=> SELECT * FROM pg_catalog.pg_cast WHERE oid = 17166;
 castsource | casttarget | castfunc | castcontext | castmethod
------------+------------+----------+-------------+------------
        869 |      16417 |    16441 | a           | f
(1 row)

aible=> SELECT * FROM pg_catalog.pg_cast WHERE oid = 17166;
 castsource | casttarget | castfunc | castcontext | castmethod
------------+------------+----------+-------------+------------
        869 |      16417 |    16441 | a           | f
(1 row)

aible=> SELECT * FROM pg_catalog.pg_extension WHERE oid = 16408;
 extname | extowner | extnamespace | extrelocatable | extversion | extconfig | extcondition
---------+----------+--------------+----------------+------------+-----------+--------------
 citext  |       10 |        16405 | t              | 1.4        |           |
(1 row)

aible=> SELECT * FROM pg_catalog.pg_cast WHERE oid = 17166;
 castsource | casttarget | castfunc | castcontext | castmethod
------------+------------+----------+-------------+------------
        869 |      16417 |    16441 | a           | f
(1 row)

aible=> SELECT typname FROM pg_catalog.pg_type WHERE oid = 869;
 typname
---------
 inet
(1 row)

aible=>
aible=> SELECT typname FROM pg_catalog.pg_type WHERE oid = 16417;
 typname
---------
 citext
(1 row)

aible=>

aible=> SELECT proname from pg_catalog.pg_proc WHERE oid = 16441;
 proname
---------
 citext
(1 row)

aible=> SELECT typname FROM pg_catalog.pg_type WHERE oid = 869;
 typname
---------
 inet
(1 row)

aible=>
```

Can you doublecheck my analysis? it looks almost like as if there's an invalid pg_depends that errorneously assigns a inet -> citext cast but has bonded to an unrelated enum!

**Comment by autumnjolitz** [comment]
To move forwards, I renamed the errant enum via `ALTER TYPE blueprint_outcome_behaviors RENAME TO broken_blueprint_behaviors;`

Then re-ran migra and let it apply the working enum. I'm still surprised at this entire debugging adventure!

**Comment by emmanuel** [comment]
@autumnjolitz thank you for documenting your process and your findings. 

I've never debugged this sort of issue through the `pg_catalog` before, so it was very informative to me to see several of the queries that I would need to diagnose related issues.

**Comment by djrobstep** [comment]
Closing this for now as it's not reproducible. If the problem flares up again, feel free to reopen.
