### ISSUE TITLE
May 8 release breaks for some schemas

### ISSUE THREAD

**Issue by gwn** [djrobstep/migra#128]
Hey,

Release 1.0.1588917048 on PyPI causes the following error for my schema:

```
Traceback (most recent call last):
  File "/home/gwn/.local/bin/migra", line 8, in <module>
    sys.exit(do_command())
  File "/home/gwn/.local/lib/python3.8/site-packages/migra/command.py", line 101, in do_command
    status = run(args)
  File "/home/gwn/.local/lib/python3.8/site-packages/migra/command.py", line 78, in run
    m.add_all_changes(privileges=args.with_privileges)
  File "/home/gwn/.local/lib/python3.8/site-packages/migra/migra.py", line 72, in add_all_changes
    self.add(self.changes.triggers(drops_only=True))
  File "/home/gwn/.local/lib/python3.8/site-packages/migra/changes.py", line 317, in get_trigger_changes
    deps_modified = [
  File "/home/gwn/.local/lib/python3.8/site-packages/migra/changes.py", line 320, in <listcomp>
    if v.quoted_full_selectable_name in modified_tables_and_other
AttributeError: 'InspectedTrigger' object has no attribute 'quoted_full_selectable_name'
Traceback (most recent call last):
  File "/home/gwn/.local/bin/migra", line 8, in <module>
    sys.exit(do_command())
  File "/home/gwn/.local/lib/python3.8/site-packages/migra/command.py", line 101, in do_command
    status = run(args)
  File "/home/gwn/.local/lib/python3.8/site-packages/migra/command.py", line 78, in run
    m.add_all_changes(privileges=args.with_privileges)
  File "/home/gwn/.local/lib/python3.8/site-packages/migra/migra.py", line 72, in add_all_changes
    self.add(self.changes.triggers(drops_only=True))
  File "/home/gwn/.local/lib/python3.8/site-packages/migra/changes.py", line 317, in get_trigger_changes
    deps_modified = [
  File "/home/gwn/.local/lib/python3.8/site-packages/migra/changes.py", line 320, in <listcomp>
    if v.quoted_full_selectable_name in modified_tables_and_other
AttributeError: 'InspectedTrigger' object has no attribute 'quoted_full_selectable_name'
```

This doesn't happen in previous releases. I can't share the schema as it's private but I hope the release id and the error message helps identifying the problem.

My schema contains several tables, views, triggers and enum types.

**Comment by djrobstep** [comment]
Hmmm.... can you confirm you're running the latest version of `schemainspect`? That property should exist on `InspectedTrigger` with the latest `schemainspect` release.

**Comment by djrobstep** [comment]
Also the latest migra release on pypi is `1.0.1588932782` which differs from the version you mention?

**Comment by gwn** [comment]
> Hmmm.... can you confirm you're running the latest version of schemainspect? That property should exist on InspectedTrigger with the latest schemainspect release.

Ok, will do this soon and inform you.


> Also the latest migra release on pypi is 1.0.1588932782 which differs from the version you mention?

Yes, it's a previous release from the same day, according to the release history in PyPI:
https://pypi.org/project/migra/1.0.1575954682/#history

I shared the id of the former release's id, because it's the first release that breaks. The next release breaks as well.

**Comment by djrobstep** [comment]
Hoping all is well with this now! If not, let me know
