### ISSUE TITLE
AttributeError: 'Session' object has no attribute 'engine'

### ISSUE THREAD

**Issue by jesperordrup** [djrobstep/migra#129]
This error when running the dockercommand on a specific repo

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/schemainspect/misc.py", line 9, in connection_from_s_or_c
    s_or_c.engine
AttributeError: 'Session' object has no attribute 'engine'
```

https://stackoverflow.com/questions/20201809/sqlalchemy-flask-attributeerror-session-object-has-no-attribute-model-chan

**Comment by djrobstep** [comment]
What is the command/code that you're running (sanitize any sensitive details)?

**Comment by jesperordrup** [comment]
Thx

docker run djrobstep/migra migra  postgres:///production postgres:///development > file.sql

I'm running on windows.

I just realised that the versions are different:
The Dev server is a windows installed postgres 12.x
The prod is a dokku service postgres version 11.x
I can run migra fine between two of the same versions.

**Comment by djrobstep** [comment]
I'm puzzled because you're seeing an `AttributeError` and yet that is explicitly handled in the code for that line:

```
def connection_from_s_or_c(s_or_c):  # pragma: no cover
    try:
        s_or_c.engine
        return s_or_c

    except AttributeError:
        return s_or_c.connection()
```

Could you supply a more complete stack trace?

**Comment by jesperordrup** [comment]
Here goes:

```
docker run djrobstep/migra migra --unsafe postgres:///production postgres:///develop  
```


```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/schemainspect/misc.py", line 9, in connection_from_s_or_c
    s_or_c.engine
AttributeError: 'Session' object has no attribute 'engine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2285, in _wrap_pool_connect
    return fn()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 773, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 657, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 652, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 490, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.5432"?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/migra", line 8, in <module>
    sys.exit(do_command())
  File "/usr/lib/python3.6/site-packages/migra/command.py", line 101, in do_command
    status = run(args)
  File "/usr/lib/python3.6/site-packages/migra/command.py", line 72, in run
    m = Migration(ac0, ac1, schema=schema)
  File "/usr/lib/python3.6/site-packages/migra/migra.py", line 29, in __init__
    self.changes.i_target = get_inspector(x_target, schema=schema)
  File "/usr/lib/python3.6/site-packages/schemainspect/get.py", line 12, in get_inspector
    c = connection_from_s_or_c(x)
  File "/usr/lib/python3.6/site-packages/schemainspect/misc.py", line 13, in connection_from_s_or_c
    return s_or_c.connection()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1133, in connection
    execution_options=execution_options,
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1139, in _connection_for_bind
    engine, execution_options
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 432, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2251, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2289, in _wrap_pool_connect
    e, dialect, self
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1555, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2285, in _wrap_pool_connect
    return fn()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 773, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 657, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 652, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 490, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

(Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by djrobstep** [comment]
OK, what that is telling you is simply that it cannot connect to your database. Doublee-check your connection string and verify that it it works from within a container.

**Comment by jesperordrup** [comment]
Thats strange - i copy the exact same connectstring to psql command and I connect without problems

**Comment by mortifia** [comment]
ha have the same bug with dbeaver connect work

**Comment by Flor91** [comment]
I am having the same issue with 2 databases with different versions

**Comment by ertongcan** [comment]
I am having the same issue when connection string url contains sslmode and certificates paths

**Comment by ertongcan** [comment]
> Here goes:
> 
> ```
> docker run djrobstep/migra migra --unsafe postgres:///production postgres:///develop  
> ```
> 
> ```
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/schemainspect/misc.py", line 9, in connection_from_s_or_c
>     s_or_c.engine
> AttributeError: 'Session' object has no attribute 'engine'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2285, in _wrap_pool_connect
>     return fn()
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 363, in connect
>     return _ConnectionFairy._checkout(self)
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 773, in _checkout
>     fairy = _ConnectionRecord.checkout(pool)
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
>     rec = pool._do_get()
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
>     self._dec_overflow()
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
>     exc_value, with_traceback=exc_tb,
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
>     raise exception
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
>     return self._create_connection()
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
>     return _ConnectionRecord(self)
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
>     self.__connect(first_connect_check=True)
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 657, in __connect
>     pool.logger.debug("Error on connect(): %s", e)
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
>     exc_value, with_traceback=exc_tb,
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
>     raise exception
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 652, in __connect
>     connection = pool._invoke_creator(self)
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
>     return dialect.connect(*cargs, **cparams)
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 490, in connect
>     return self.dbapi.connect(*cargs, **cparams)
>   File "/usr/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
>     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
> psycopg2.OperationalError: could not connect to server: No such file or directory
>         Is the server running locally and accepting
>         connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
> 
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/bin/migra", line 8, in <module>
>     sys.exit(do_command())
>   File "/usr/lib/python3.6/site-packages/migra/command.py", line 101, in do_command
>     status = run(args)
>   File "/usr/lib/python3.6/site-packages/migra/command.py", line 72, in run
>     m = Migration(ac0, ac1, schema=schema)
>   File "/usr/lib/python3.6/site-packages/migra/migra.py", line 29, in __init__
>     self.changes.i_target = get_inspector(x_target, schema=schema)
>   File "/usr/lib/python3.6/site-packages/schemainspect/get.py", line 12, in get_inspector
>     c = connection_from_s_or_c(x)
>   File "/usr/lib/python3.6/site-packages/schemainspect/misc.py", line 13, in connection_from_s_or_c
>     return s_or_c.connection()
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1133, in connection
>     execution_options=execution_options,
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1139, in _connection_for_bind
>     engine, execution_options
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 432, in _connection_for_bind
>     conn = bind._contextual_connect()
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2251, in _contextual_connect
>     self._wrap_pool_connect(self.pool.connect, None),
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2289, in _wrap_pool_connect
>     e, dialect, self
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1555, in _handle_dbapi_exception_noconnection
>     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
>     raise exception
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2285, in _wrap_pool_connect
>     return fn()
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 363, in connect
>     return _ConnectionFairy._checkout(self)
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 773, in _checkout
>     fairy = _ConnectionRecord.checkout(pool)
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
>     rec = pool._do_get()
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
>     self._dec_overflow()
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
>     exc_value, with_traceback=exc_tb,
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
>     raise exception
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
>     return self._create_connection()
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
>     return _ConnectionRecord(self)
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
>     self.__connect(first_connect_check=True)
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 657, in __connect
>     pool.logger.debug("Error on connect(): %s", e)
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
>     exc_value, with_traceback=exc_tb,
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
>     raise exception
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 652, in __connect
>     connection = pool._invoke_creator(self)
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
>     return dialect.connect(*cargs, **cparams)
>   File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 490, in connect
>     return self.dbapi.connect(*cargs, **cparams)
>   File "/usr/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
>     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
> sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: No such file or directory
>         Is the server running locally and accepting
>         connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
> 
> (Background on this error at: http://sqlalche.me/e/e3q8)
> ```

I thinnk this is also realted to my above comment because I am getting the same stack trace with connection string including ssllmode config

**Comment by djrobstep** [comment]
Remember that the command is running within a container. Double-check your connection string and verify that it it works from within a container.

**Comment by sseppola** [comment]
If running migra in Docker add `--network host` to the `docker run` command in order to access connections as if running on your machine.

```
docker run --network host djrobstep/migra migra --unsafe postgres:///production postgres:///develop  
```
