### ISSUE TITLE
Error when database has a view selecting from a foreign table

### ISSUE THREAD

**Issue by h0gar** [djrobstep/migra#130]
**Here is the error:**
```
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\Scripts\migra.exe\__main__.py", line 7, in <module>
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\migra\command.py", line 101, in do_command
    status = run(args)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\migra\command.py", line 72, in run
    m = Migration(ac0, ac1, schema=schema)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\migra\migra.py", line 22, in __init__
    self.changes.i_from = get_inspector(x_from, schema=schema)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\schemainspect\get.py", line 18, in get_inspector
    inspected = ic(c)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\schemainspect\pg\obj.py", line 724, in __init__
    super(PostgreSQL, self).__init__(c, include_internal)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\schemainspect\inspector.py", line 25, in __init__
    self.load_all()
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\schemainspect\pg\obj.py", line 733, in load_all
    self.load_deps()
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\schemainspect\pg\obj.py", line 805, in load_deps
    self.selectables[x_dependent_on].dependents.append(x)
KeyError: '"public"."foreign_user"'
```

**How to reproduce:**

Create a database with one table:
```
CREATE TABLE "public"."user" (
    "id" integer NOT NULL,
    "email" character varying(255)
) WITH (oids = false);
```

Create a second database and run these queries:
```
CREATE EXTENSION postgres_fdw;
CREATE SERVER foreign_server FOREIGN DATA WRAPPER postgres_fdw OPTIONS (host '127.0.0.1', port '5432', dbname 'foreign_database');
CREATE USER MAPPING FOR postgres SERVER foreign_server OPTIONS (user 'postgres', password 'a_password');

CREATE FOREIGN TABLE foreign_user (
    id integer NOT NULL,
    email character varying(255)
)
        SERVER foreign_server
        OPTIONS (schema_name 'public', table_name 'user');
CREATE VIEW "user" AS select * from foreign_user;
```

Then run migra to generate a diff between this database and another one.

**Comment by djrobstep** [comment]
Hey, thanks heaps for reporting this and providing a good test case. `migra` doesn't (yet) handle FDWs well, but obviously still shouldn't be erroring out like this.

I hope to have a fix for this released soon.

**Comment by ryanberckmans** [comment]
I'd also like to use `migra` with FDWs :)

**Comment by fraywing** [comment]
Migra is broken for us as of version `1.0.1588932782`

We get:

```
Traceback (most recent call last):
  File "/usr/local/bin/migra", line 10, in <module>
    sys.exit(do_command())
  File "/usr/local/lib/python3.7/site-packages/migra/command.py", line 101, in do_command
    status = run(args)
  File "/usr/local/lib/python3.7/site-packages/migra/command.py", line 72, in run
    m = Migration(ac0, ac1, schema=schema)
  File "/usr/local/lib/python3.7/site-packages/migra/migra.py", line 23, in __init__
    self.changes.i_from = get_inspector(x_from, schema=schema)
  File "/usr/local/lib/python3.7/site-packages/schemainspect/get.py", line 18, in get_inspector
    inspected = ic(c)
  File "/usr/local/lib/python3.7/site-packages/schemainspect/pg/obj.py", line 950, in __init__
    super(PostgreSQL, self).__init__(c, include_internal)
  File "/usr/local/lib/python3.7/site-packages/schemainspect/inspector.py", line 25, in __init__
    self.load_all()
  File "/usr/local/lib/python3.7/site-packages/schemainspect/pg/obj.py", line 967, in load_all
    self.load_deps()
  File "/usr/local/lib/python3.7/site-packages/schemainspect/pg/obj.py", line 1044, in load_deps
    dependency = self.selectables[dep_name]
KeyError: '"topology"."layer"'
```

when I downgrade to `1.0.1575954682` it works.

**Comment by djrobstep** [comment]
@ryanberckmans It's definitely in the pipeline, and a reasonably high priority, can't promise exactly when at this stage tho.

**Comment by djrobstep** [comment]
This should be fixed as of the latest release, let me know if there's any issues. Still doesn't support FDWs but shouldn't error out.
