### ISSUE TITLE
KeyError: '"topology"."layer"'

### ISSUE THREAD

**Issue by andypoorman** [djrobstep/migra#132]
I was trying to create a diff with `Version 1.0.1588932782` and received the following error. A co-worker of mine was able to execute the same command with no issues using version `Version 1.0.1575954682`. He is now also experiencing the issue after upgrading to the latest. FWIW, downgrading did not fix the problem. Perhaps it's an issue with the version of `schemainspect`?

Has anyone else encountered this?

```
Traceback (most recent call last):
  File "/usr/local/bin/migra", line 8, in <module>
    sys.exit(do_command())
  File "/usr/local/lib/python3.7/site-packages/migra/command.py", line 101, in do_command
    status = run(args)
  File "/usr/local/lib/python3.7/site-packages/migra/command.py", line 72, in run
    m = Migration(ac0, ac1, schema=schema)
  File "/usr/local/lib/python3.7/site-packages/migra/migra.py", line 22, in __init__
    self.changes.i_from = get_inspector(x_from, schema=schema)
  File "/usr/local/lib/python3.7/site-packages/schemainspect/get.py", line 18, in get_inspector
    inspected = ic(c)
  File "/usr/local/lib/python3.7/site-packages/schemainspect/pg/obj.py", line 950, in __init__
    super(PostgreSQL, self).__init__(c, include_internal)
  File "/usr/local/lib/python3.7/site-packages/schemainspect/inspector.py", line 25, in __init__
    self.load_all()
  File "/usr/local/lib/python3.7/site-packages/schemainspect/pg/obj.py", line 967, in load_all
    self.load_deps()
  File "/usr/local/lib/python3.7/site-packages/schemainspect/pg/obj.py", line 1044, in load_deps
    dependency = self.selectables[dep_name]
KeyError: '"topology"."layer"'
```

**Comment by djrobstep** [comment]
Thanks for filing this issue. What kind of object is `topology.layer` in your schema?

**Comment by andypoorman** [comment]
It's part of PostGis: https://postgis.net/docs/manual-dev/Topology.html

It's been working up until now.

**Comment by fraywing** [comment]
I'm having the same issue! 

In my schema, it's just a table.

<img width="302" alt="Screen Shot 2020-06-15 at 5 11 35 PM" src="https://user-images.githubusercontent.com/1855967/84717660-4e47bc00-af2b-11ea-812c-a8f4dd2241a4.png">

**Comment by djrobstep** [comment]
This may be a regression based on recent changes to the function inspection logic. Do you have a procedures/functions that refer to this table? 

This should be a straightforward fix, I hope to roll it out shortly.

**Comment by djrobstep** [comment]
This should now be fixed as of the latest release. Any further issues let me know.
