### ISSUE TITLE
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:connectiontype

### ISSUE THREAD

**Issue by BhimAle** [djrobstep/migra#141]
I am getting error below on Windows Machine

```
migra connectiontype://postgres:postgres@localhost/test_from connectiontype://postgres:postgres@localhost/test_to
Traceback (most recent call last):
  File "c:\python3.7\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python3.7\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python3.7\Scripts\migra.exe\__main__.py", line 9, in <module>
  File "c:\python3.7\lib\site-packages\migra\command.py", line 101, in do_command
    status = run(args)
  File "c:\python3.7\lib\site-packages\migra\command.py", line 71, in run
    with arg_context(args.dburl_from) as ac0, arg_context(args.dburl_target) as ac1:
  File "c:\python3.7\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "c:\python3.7\lib\site-packages\migra\command.py", line 19, in arg_context
    with S(x) as s:
  File "c:\python3.7\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "c:\python3.7\lib\site-packages\sqlbag\sqla.py", line 141, in S
    Session = get_scoped_session_maker(*args, **kwargs)
  File "c:\python3.7\lib\site-packages\sqlbag\sqla.py", line 163, in get_scoped_session_maker
    sessionmaker(bind=create_engine(*args, **kwargs)), scopefunc=scopefunc
  File "c:\python3.7\lib\site-packages\sqlalchemy\engine\__init__.py", line 500, in create_engine
    return strategy.create(*args, **kwargs)
  File "c:\python3.7\lib\site-packages\sqlalchemy\engine\strategies.py", line 61, in create
    entrypoint = u._get_entrypoint()
  File "c:\python3.7\lib\site-packages\sqlalchemy\engine\url.py", line 172, in _get_entrypoint
    cls = registry.load(name)
  File "c:\python3.7\lib\site-packages\sqlalchemy\util\langhelpers.py", line 268, in load
    "Can't load plugin: %s:%s" % (self.group, name)
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:connectiontype
```

**Comment by djrobstep** [comment]
connectiontype needs to be set to the name of the type of database you are connecting to, in this case "postgresql".  More information on database URLs is here: https://docs.sqlalchemy.org/en/13/core/engines.html#database-urls

**Comment by BhimAle** [comment]
Thank youo @djrobstep  :)
