### ISSUE TITLE
[BUG] Migra crashes when hitting custom types

### ISSUE THREAD

**Issue by tvarsis** [djrobstep/migra#171]
I have a custom type like this:

```
CREATE TYPE "public"."time_period_type" AS (
  "start_date" timestamptz(6),
  "end_date" timestamptz(6)
);
```

That is then use in some views. When I try to run a schema diff between two schemas (that both already have that type as well) migra crashes and does not finish comparison:

```
Traceback (most recent call last):
  File "/home/username/.local/bin//migra", line 8, in <module>
    sys.exit(do_command())
  File "/home/username/.local/lib/python3.8/site-packages/migra/command.py", line 108, in do_command
    status = run(args)
  File "/home/username/.local/lib/python3.8/site-packages/migra/command.py", line 79, in run
    m = Migration(ac0, ac1, schema=schema, exclude_schema=exclude_schema)
  File "/home/username/.local/lib/python3.8/site-packages/migra/migra.py", line 25, in __init__
    self.changes.i_from = get_inspector(
  File "/home/username/.local/lib/python3.8/site-packages/schemainspect/get.py", line 20, in get_inspector
    inspected = ic(c)
  File "/home/username/.local/lib/python3.8/site-packages/schemainspect/pg/obj.py", line 1073, in __init__
    super(PostgreSQL, self).__init__(c, include_internal)
  File "/home/username/.local/lib/python3.8/site-packages/schemainspect/inspector.py", line 25, in __init__
    self.load_all()
  File "/home/username/.local/lib/python3.8/site-packages/schemainspect/pg/obj.py", line 1090, in load_all
    self.load_deps()
  File "/home/username/.local/lib/python3.8/site-packages/schemainspect/pg/obj.py", line 1165, in load_deps
    self.selectables[x_dependent_on].dependents.append(x)
KeyError: '"public"."time_period_type"'
```

**Comment by jokimaki** [comment]
I was also hit by this bug. As a workaround one can build a custom docker image with @venatir's patch applied with the following Dockerfile:

```
FROM djrobstep/migra:3.0.1621480950

RUN apk add --no-cache patch \
  && cd /usr/local/lib/python3.9/site-packages/schemainspect/pg \
  && echo -e "--- obj.py\n\
+++ obj.patched.py\n\
@@ -1078,6 +1078,7 @@\n\
         self.load_functions()\n\
         self.selectables = od()\n\
         self.selectables.update(self.relations)\n\
+        self.selectables.update(self.composite_types)\n\
         self.selectables.update(self.functions)\n\
\n\
         self.load_privileges()" | patch
```

**Comment by djrobstep** [comment]
Composite types still aren't fully handled but this should at least not crash now.
