### ISSUE TITLE
`TypeError: can't intern String` Build Error

### ISSUE THREAD

**Issue by jaredramirez** [djrobstep/migra#193]
Hey there,

I'm trying to build this project with nix, using [`poetry2Nix`](https://github.com/nix-community/poetry2nix). I'm not super familiar with Python in general, but I'm hitting this error:
```
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /nix/store/b83i8vc1p3rn15zxd3zvlbjgs43dyvw6-python3-3.7.11/bin/python3.7 /nix/store/332r9d1cllhpkrbhfd3l82dzypljgrsz-python3.7-pip-20.2.4/lib/python3.7/site-packages/pip/_vendor/
         cwd: /private/tmp/nix-build-python3.7-migra-3.0.drv-0/pip-req-build-9z4ffe_j
    Complete output (20 lines):
    Traceback (most recent call last):
      File "/nix/store/332r9d1cllhpkrbhfd3l82dzypljgrsz-python3.7-pip-20.2.4/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/nix/store/332r9d1cllhpkrbhfd3l82dzypljgrsz-python3.7-pip-20.2.4/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/nix/store/332r9d1cllhpkrbhfd3l82dzypljgrsz-python3.7-pip-20.2.4/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/nix/store/16ifjb801x6ax4zg7s8sqf2jbnmjggv0-python3.7-poetry-core-1.0.2/lib/python3.7/site-packages/poetry/core/masonry/api.py", line 43, in prepare_metadata_for_build_wheel
        poetry = Factory().create_poetry(Path(".").resolve(), with_dev=False)
      File "/nix/store/16ifjb801x6ax4zg7s8sqf2jbnmjggv0-python3.7-poetry-core-1.0.2/lib/python3.7/site-packages/poetry/core/factory.py", line 71, in create_poetry
        package.readme = Path(poetry_file.parent) / local_config["readme"]
      File "/nix/store/prkk0rcclijlyfbxw7hs0hdnl92i55a0-python3.7-pathlib-1.0.1/lib/python3.7/site-packages/pathlib.py", line 853, in __truediv__
        return self._make_child((key,))
      File "/nix/store/prkk0rcclijlyfbxw7hs0hdnl92i55a0-python3.7-pathlib-1.0.1/lib/python3.7/site-packages/pathlib.py", line 643, in _make_child
        drv, root, parts = self._parse_args(args)
      File "/nix/store/prkk0rcclijlyfbxw7hs0hdnl92i55a0-python3.7-pathlib-1.0.1/lib/python3.7/site-packages/pathlib.py", line 606, in _parse_args
        return cls._flavour.parse_parts(parts)
      File "/nix/store/prkk0rcclijlyfbxw7hs0hdnl92i55a0-python3.7-pathlib-1.0.1/lib/python3.7/site-packages/pathlib.py", line 93, in parse_parts
        parsed.append(intern(rel))
    TypeError: can't intern String
```

Do you have any idea what the problem could be?

**Comment by djrobstep** [comment]
Hello, sorry for the slow reply on this one - but this doesn't look like a migra bug, it's possibly a poetry thing? Hope you wound up solving it, and if it does turn out to be a problem this end, please do reopen.
