### ISSUE TITLE
psycopg2 should be a requirement

### ISSUE THREAD

**Issue by slafs** [djrobstep/migra#2]
Since this tool uses it by default. After fresh install via `pipsi` I got this:
```
$ migra --help
Traceback (most recent call last):
  File "/home/slafs/.local/bin/migra", line 7, in <module>
    from migra import do_command
  File "/home/slafs/.local/venvs/migra/local/lib/python2.7/site-packages/migra/__init__.py", line 5, in <module>
    from .migra import Migration
  File "/home/slafs/.local/venvs/migra/local/lib/python2.7/site-packages/migra/migra.py", line 3, in <module>
    from sqlbag import raw_execute
  File "/home/slafs/.local/venvs/migra/local/lib/python2.7/site-packages/sqlbag/__init__.py", line 27, in <module>
    from . import pg
  File "/home/slafs/.local/venvs/migra/local/lib/python2.7/site-packages/sqlbag/pg/__init__.py", line 4, in <module>
    from .postgresql import \
  File "/home/slafs/.local/venvs/migra/local/lib/python2.7/site-packages/sqlbag/pg/postgresql.py", line 7, in <module>
    from psycopg2 import errorcodes as pgerrorcodes
ImportError: No module named psycopg2
````

**Comment by slafs** [comment]
I'm a muppet and should read https://github.com/djrobstep/migra#installation first ;). Sorry for the noise.
