### ISSUE TITLE
no module named six

### ISSUE THREAD

**Issue by revington** [djrobstep/migra#58]
```
Traceback (most recent call last):
  File "/usr/bin/migra", line 7, in <module>
    from migra import do_command
  File "/usr/lib/python2.7/site-packages/migra/__init__.py", line 5, in <module>
    from .migra import Migration
  File "/usr/lib/python2.7/site-packages/migra/migra.py", line 3, in <module>
    from schemainspect import DBInspector, get_inspector
  File "/usr/lib/python2.7/site-packages/schemainspect/__init__.py", line 4, in <module>
    from .inspected import ColumnInfo, Inspected
  File "/usr/lib/python2.7/site-packages/schemainspect/inspected.py", line 1, in <module>
    from .misc import AutoRepr, quoted_identifier
  File "/usr/lib/python2.7/site-packages/schemainspect/misc.py", line 3, in <module>
    import six
ImportError: No module named six

```
But six is already installed
```
Requirement already up-to-date: migra in /usr/lib/python2.7/site-packages (1.0.1542697120)
Requirement already satisfied, skipping upgrade: schemainspect in /usr/lib/python2.7/site-packages (from migra) (0.1.1525395046)
Requirement already satisfied, skipping upgrade: six in /usr/lib/python2.7/site-packages (from migra) (1.10.0)
Requirement already satisfied, skipping upgrade: sqlbag in /usr/lib/python2.7/site-packages (from migra) (0.1.1541129705)
Requirement already satisfied, skipping upgrade: sqlalchemy in /usr/lib/python2.7/site-packages (from schemainspect->migra) (1.2.7)
Requirement already satisfied, skipping upgrade: pathlib in /usr/lib/python2.7/site-packages (from sqlbag->migra) (1.0.1)
```

Both migra and six (and the other deps) are installed on /usr/lib/python2.7

**Comment by revington** [comment]
fixed with 
```
# pip install -U awscli
```

**Comment by djrobstep** [comment]
Solved and don't think this is `migra`-related, so closing for now.
