### ISSUE TITLE
Failing with postgres 9.6

### ISSUE THREAD

**Issue by revington** [djrobstep/migra#59]
Got the following error with postgres 9.6
```
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column c.relpartbound does not exist
```
Is there anything I can do about it? 

Full trace below
```
Traceback (most recent call last):
  File "/usr/bin/migra", line 11, in <module>
    sys.exit(do_command())
  File "/usr/lib/python2.7/site-packages/migra/command.py", line 101, in do_command
    status = run(args)
  File "/usr/lib/python2.7/site-packages/migra/command.py", line 72, in run
    m = Migration(ac0, ac1, schema=schema)
  File "/usr/lib/python2.7/site-packages/migra/migra.py", line 22, in __init__
    self.changes.i_from = get_inspector(x_from, schema=schema)
  File "/usr/lib/python2.7/site-packages/schemainspect/get.py", line 18, in get_inspector
    inspected = ic(c)
  File "/usr/lib/python2.7/site-packages/schemainspect/pg/obj.py", line 536, in __init__
    super(PostgreSQL, self).__init__(c, include_internal)
  File "/usr/lib/python2.7/site-packages/schemainspect/inspector.py", line 25, in __init__
    self.load_all()
  File "/usr/lib/python2.7/site-packages/schemainspect/pg/obj.py", line 540, in load_all
    self.load_all_relations()
  File "/usr/lib/python2.7/site-packages/schemainspect/pg/obj.py", line 648, in load_all_relations
    q = self.c.execute(self.ALL_RELATIONS_QUERY)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column c.relpartbound does not exist
LINE 36:         case when c.relpartbound is not null then
                           ^
 [SQL: 'with extension_oids as (\n  select\n      objid\n  from\n      pg_depend d\n  WHERE\n      d.refclassid = \'pg_extension\'::regclass\n), enums as (\n\n  SELECT\n    t.oid as enum_oid,\n    n.nspname as "schema",\n    pg_catalog.format_type(t.oid, NULL) AS "name"\n  FROM pg_catalog.pg_type t\n       LEFT JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace\n       left outer join extension_oids e\n         on t.oid = e.objid\n  WHERE\n    t.typcategory = \'E\'\n    and e.objid is null\n     and n.nspname not in (\'pg_catalog\', \'information_schema\', \'pg_toast\')\n     and n.nspname not like \'pg_temp_%%\' and n.nspname not like \'pg_toast_temp_%%\'\n    AND pg_catalog.pg_type_is_visible(t.oid)\n  ORDER BY 1, 2\n),\nr as (\n    select\n        c.relname as name,\n        n.nspname as schema,\n        c.relkind as relationtype,\n        c.oid as oid,\n        case when c.relkind in (\'m\', \'v\') then\n          pg_get_viewdef(c.oid)\n        else null end\n          as definition,\n        case when c.relpartbound is not null then\n          (SELECT\n              \'"\' || nmsp_parent.nspname || \'"."\' || parent.relname || \'"\' as parent\n          FROM pg_inherits\n              JOIN pg_class parent            ON pg_inherits.inhparent = parent.oid\n              JOIN pg_class child             ON pg_inherits.inhrelid   = child.oid\n              JOIN pg_namespace nmsp_parent   ON nmsp_parent.oid  = parent.relnamespace\n              JOIN pg_namespace nmsp_child    ON nmsp_child.oid   = child.relnamespace\n          where child.oid = c.oid\n        )\n        end as parent_table,\n        case when c.relpartbound is not null then\n          pg_get_expr(c.relpartbound, c.oid, true)\n        when c.relhassubclass is not null then\n          pg_catalog.pg_get_partkeydef(c.oid)\n        end\n        as partition_def\n    from\n        pg_catalog.pg_class c\n        inner join pg_catalog.pg_namespace n\n          ON n.oid = c.relnamespace\n        left outer join extension_oids e\n          on c.oid = e.objid\n    where c.relkind in (\'r\', \'v\', \'m\', \'c\', \'p\')\n     and e.objid is null\n     and n.nspname not in (\'pg_catalog\', \'information_schema\', \'pg_toast\')\n     and n.nspname not like \'pg_temp_%%\' and n.nspname not like \'pg_toast_temp_%%\'\n)\nselect\n    r.relationtype,\n    r.schema,\n    r.name,\n    r.definition as definition,\n    a.attnum as position_number,\n    a.attname as attname,\n    a.attnotnull as not_null,\n    a.atttypid::regtype AS datatype,\n    (SELECT c.collname FROM pg_catalog.pg_collation c, pg_catalog.pg_type t\n     WHERE c.oid = a.attcollation AND t.oid = a.atttypid AND a.attcollation <> t.typcollation) AS collation,\n    pg_get_expr(ad.adbin, ad.adrelid) as defaultdef,\n    r.oid as oid,\n    format_type(atttypid, atttypmod) AS datatypestring,\n    e.enum_oid is not null as is_enum,\n    e.name as enum_name,\n    e.schema as enum_schema,\n    pg_catalog.obj_description(r.oid) as comment,\n    r.parent_table,\n    r.partition_def\nFROM\n    r\n    left join pg_catalog.pg_attribute a\n        on r.oid = a.attrelid and a.attnum > 0\n    left join pg_catalog.pg_attrdef ad\n        on a.attrelid = ad.adrelid\n        and a.attnum = ad.adnum\n    left join enums e\n      on a.atttypid = e.enum_oid\nwhere a.attisdropped is not true\n and r.schema not in (\'pg_catalog\', \'information_schema\', \'pg_toast\')\n and r.schema not like \'pg_temp_%%\' and r.schema not like \'pg_toast_temp_%%\'\norder by relationtype, r.schema, r.name, position_number;\n'] (Background on this error at: http://sqlalche.me/e/f405)
```

**Comment by djrobstep** [comment]
Thanks for reporting this. I recently added support for table partitioning (new feature in 10/11), but as you've discovered, this breaks support for postgres 9.x.

I will update the docs to note this, but unfortunately I don't have the time to fix this straight away, so in the short term your options are:

- upgrade your version of postgres to 10 or 11
- downgrade your version of migra and schemainspect to older versions from partitioning support was added (any releases older than a week should work)

I strongly recommend upgrading to postgres 10. I know this isn't always possible, but I generally prioritize new features of backwards compatibility.

**Comment by revington** [comment]
@AUTOMATIC1111 Great! that worked!

**Comment by anacrolix** [comment]
Probs can close this if it's not actionable :P

**Comment by djrobstep** [comment]
I'll add a note about this to the docs.

@anacrolix long time no see m8, how are you going these days?

**Comment by adnelson** [comment]
I'm using migra for the first time with Postgres 9.6.12 and running into the same error.

* `migra` is version `1.0.11554608452`
* `schemainspect` is version `1.0.1556103540`

Output:

```
⇒  migra postgresql://localhost:5999/sheltie postgresql://localhost:5999/sheltie-test
Traceback (most recent call last):
  File "/nix/store/apf8j56vk7yq0lw8rys8adz0j7256wwj-python3.7-SQLAlchemy-1.3.6/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/nix/store/apf8j56vk7yq0lw8rys8adz0j7256wwj-python3.7-SQLAlchemy-1.3.6/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: column c.relpartbound does not exist
LINE 36:         case when c.relpartbound is not null then
                           ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nix/store/2zi9g3a3h84vrh2825jz9qwjkds8ziks-python3.7-migra-1.0.11554608452/bin/.migra-wrapped", line 11, in <module>
    sys.exit(do_command())
  File "/nix/store/2zi9g3a3h84vrh2825jz9qwjkds8ziks-python3.7-migra-1.0.11554608452/lib/python3.7/site-packages/migra/command.py", line 101, in do_command
    status = run(args)
  File "/nix/store/2zi9g3a3h84vrh2825jz9qwjkds8ziks-python3.7-migra-1.0.11554608452/lib/python3.7/site-packages/migra/command.py", line 72, in run
    m = Migration(ac0, ac1, schema=schema)
  File "/nix/store/2zi9g3a3h84vrh2825jz9qwjkds8ziks-python3.7-migra-1.0.11554608452/lib/python3.7/site-packages/migra/migra.py", line 22, in __init__
    self.changes.i_from = get_inspector(x_from, schema=schema)
  File "/nix/store/4pnvw871djda2grwcphzi7rmj4y1pmha-python3.7-schemainspect-1.0.1556103540/lib/python3.7/site-packages/schemainspect/get.py", line 18, in get_inspector
    inspected = ic(c)
  File "/nix/store/4pnvw871djda2grwcphzi7rmj4y1pmha-python3.7-schemainspect-1.0.1556103540/lib/python3.7/site-packages/schemainspect/pg/obj.py", line 718, in __init__
    super(PostgreSQL, self).__init__(c, include_internal)
  File "/nix/store/4pnvw871djda2grwcphzi7rmj4y1pmha-python3.7-schemainspect-1.0.1556103540/lib/python3.7/site-packages/schemainspect/inspector.py", line 25, in __init__
    self.load_all()
  File "/nix/store/4pnvw871djda2grwcphzi7rmj4y1pmha-python3.7-schemainspect-1.0.1556103540/lib/python3.7/site-packages/schemainspect/pg/obj.py", line 722, in load_all
    self.load_all_relations()
  File "/nix/store/4pnvw871djda2grwcphzi7rmj4y1pmha-python3.7-schemainspect-1.0.1556103540/lib/python3.7/site-packages/schemainspect/pg/obj.py", line 852, in load_all_relations
    q = self.c.execute(self.ALL_RELATIONS_QUERY)
  File "/nix/store/apf8j56vk7yq0lw8rys8adz0j7256wwj-python3.7-SQLAlchemy-1.3.6/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/nix/store/apf8j56vk7yq0lw8rys8adz0j7256wwj-python3.7-SQLAlchemy-1.3.6/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/nix/store/apf8j56vk7yq0lw8rys8adz0j7256wwj-python3.7-SQLAlchemy-1.3.6/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/nix/store/apf8j56vk7yq0lw8rys8adz0j7256wwj-python3.7-SQLAlchemy-1.3.6/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/nix/store/apf8j56vk7yq0lw8rys8adz0j7256wwj-python3.7-SQLAlchemy-1.3.6/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/nix/store/apf8j56vk7yq0lw8rys8adz0j7256wwj-python3.7-SQLAlchemy-1.3.6/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/nix/store/apf8j56vk7yq0lw8rys8adz0j7256wwj-python3.7-SQLAlchemy-1.3.6/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/nix/store/apf8j56vk7yq0lw8rys8adz0j7256wwj-python3.7-SQLAlchemy-1.3.6/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/nix/store/apf8j56vk7yq0lw8rys8adz0j7256wwj-python3.7-SQLAlchemy-1.3.6/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column c.relpartbound does not exist
LINE 36:         case when c.relpartbound is not null then
                           ^

[SQL: with extension_oids as (
  select
      objid
  from
      pg_depend d
  WHERE
      d.refclassid = 'pg_extension'::regclass
), enums as (

  SELECT
    t.oid as enum_oid,
    n.nspname as "schema",
    pg_catalog.format_type(t.oid, NULL) AS "name"
  FROM pg_catalog.pg_type t
       LEFT JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
       left outer join extension_oids e
         on t.oid = e.objid
  WHERE
    t.typcategory = 'E'
    and e.objid is null
     and n.nspname not in ('pg_catalog', 'information_schema', 'pg_toast')
     and n.nspname not like 'pg_temp_%%' and n.nspname not like 'pg_toast_temp_%%'
    AND pg_catalog.pg_type_is_visible(t.oid)
  ORDER BY 1, 2
),
r as (
    select
        c.relname as name,
        n.nspname as schema,
        c.relkind as relationtype,
        c.oid as oid,
        case when c.relkind in ('m', 'v') then
          pg_get_viewdef(c.oid)
        else null end
          as definition,
        case when c.relpartbound is not null then
          (SELECT
              '"' || nmsp_parent.nspname || '"."' || parent.relname || '"' as parent
          FROM pg_inherits
              JOIN pg_class parent            ON pg_inherits.inhparent = parent.oid
              JOIN pg_class child             ON pg_inherits.inhrelid   = child.oid
              JOIN pg_namespace nmsp_parent   ON nmsp_parent.oid  = parent.relnamespace
              JOIN pg_namespace nmsp_child    ON nmsp_child.oid   = child.relnamespace
          where child.oid = c.oid
        )
        end
        as parent_table,
        case when c.relpartbound is not null then
          pg_get_expr(c.relpartbound, c.oid, true)
        when c.relhassubclass is not null then
          pg_catalog.pg_get_partkeydef(c.oid)
        end
        as partition_def,
        c.relrowsecurity::boolean as rowsecurity,
        c.relforcerowsecurity::boolean as forcerowsecurity
    from
        pg_catalog.pg_class c
        inner join pg_catalog.pg_namespace n
          ON n.oid = c.relnamespace
        left outer join extension_oids e
          on c.oid = e.objid
    where c.relkind in ('r', 'v', 'm', 'c', 'p')
     and e.objid is null
     and n.nspname not in ('pg_catalog', 'information_schema', 'pg_toast')
     and n.nspname not like 'pg_temp_%%' and n.nspname not like 'pg_toast_temp_%%'
)
select
    r.relationtype,
    r.schema,
    r.name,
    r.definition as definition,
    a.attnum as position_number,
    a.attname as attname,
    a.attnotnull as not_null,
    a.atttypid::regtype AS datatype,
    (SELECT c.collname FROM pg_catalog.pg_collation c, pg_catalog.pg_type t
     WHERE c.oid = a.attcollation AND t.oid = a.atttypid AND a.attcollation <> t.typcollation) AS collation,
    pg_get_expr(ad.adbin, ad.adrelid) as defaultdef,
    r.oid as oid,
    format_type(atttypid, atttypmod) AS datatypestring,
    e.enum_oid is not null as is_enum,
    e.name as enum_name,
    e.schema as enum_schema,
    pg_catalog.obj_description(r.oid) as comment,
    r.parent_table,
    r.partition_def,
    r.rowsecurity,
    r.forcerowsecurity
FROM
    r
    left join pg_catalog.pg_attribute a
        on r.oid = a.attrelid and a.attnum > 0
    left join pg_catalog.pg_attrdef ad
        on a.attrelid = ad.adrelid
        and a.attnum = ad.adnum
    left join enums e
      on a.atttypid = e.enum_oid
where a.attisdropped is not true
 and r.schema not in ('pg_catalog', 'information_schema', 'pg_toast')
 and r.schema not like 'pg_temp_%%' and r.schema not like 'pg_toast_temp_%%'
order by relationtype, r.schema, r.name, position_number;
]
(Background on this error at: http://sqlalche.me/e/f405)
```
