### ISSUE TITLE
Doesn't work on Windows?

### ISSUE THREAD

**Issue by peetw** [djrobstep/migra#6]
Hi, first up - this looks like an awesome tool :) However, I'm trying to run it on Windows and I'm running into the following error:

    Traceback (most recent call last):
      File "c:\progra~3\minico~1\lib\runpy.py", line 174, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "c:\progra~3\minico~1\lib\runpy.py", line 72, in _run_code
        exec code in run_globals
      File "C:\PROGRA~3\MINICO~1\Scripts\migra.exe\__main__.py", line 5, in <module>

      File "c:\progra~3\minico~1\lib\site-packages\migra\__init__.py", line 5, in <m
    odule>
        from .migra import Migration
      File "c:\progra~3\minico~1\lib\site-packages\migra\migra.py", line 3, in <modu
    le>
        from sqlbag import raw_execute
      File "c:\progra~3\minico~1\lib\site-packages\sqlbag\__init__.py", line 23, in
    <module>
        from .createdrop import \
      File "c:\progra~3\minico~1\lib\site-packages\sqlbag\createdrop.py", line 6, in
     <module>
        import pwd
    ImportError: No module named pwd

Unfortunately the `pwd` [module](https://docs.python.org/2/library/pwd.html#module-pwd) is only available on UNIX platforms...

**Comment by djrobstep** [comment]
Hey, appreciate the report. Testing has been very limited (zero in fact) on windows so far.

This is actually a problem in `sqlbag` which is a migra dependency.

I've created an issue in that project (jlord/sheetsee.js#26), and will fix shortly.

**Comment by djrobstep** [comment]
I've now removed the pwd dependency. Haven't tested directly on windows yet but things may work better for you if you upgrade and try again?

**Comment by peetw** [comment]
Great, thanks! After updating `sqlbag`, `migra` seems to be working as intended :)
